### Create Email Notification (PENDING with template)
POST http://localhost:3000/notifications/email
Content-Type: application/json

{
  "toEmail": "wanted.dr.ali@gmail.com",
  "title": "Purchase Successful",
  "template": "purchase-success",
  "templateData": {
    "orderId": 12,
    "productLabel": "BYD segaull",
    "amount": "10000.00"
  }
}

### Send SMS via Twilio
POST http://localhost:3000/notifications/sms
Content-Type: application/json

{
  "toPhoneNumber": "+962782933735",
  "message": "Hello from Twilio trial ✅"
}